apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-webhook
  labels:
    app: webhook
    service: admission-webhook
webhooks:
  - name: admission-webhook.webhook.com
    clientConfig:
      # url: "https://admission-webhook.webhook.svc.cluster.local/inject-init-container"
      service:
        name: admission-webhook
        namespace: webhook
        path: "/"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBRENDQXVpZ0F3SUJBZ0lVSlFYQjJBTEl6dHVvUjYrRmJMK2lNaHFJeFFNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZURUxNQWtHQTFVRUJoTUNTVTR4RHpBTkJnTlZCQWdNQmt0bGNtRnNZVEVPTUF3R0ExVUVCd3dGUzI5agphR2t4RURBT0JnTlZCQW9NQjNWemRDNWpiMjB4RXpBUkJnTlZCQU1NQ25kbFltaHZiMnRmWTJFd0lCY05Nak14Ck1qQTJNakl3TVRJM1doZ1BNakk1TnpBNU1qQXlNakF4TWpkYU1GVXhDekFKQmdOVkJBWVRBa2xPTVE4d0RRWUQKVlFRSURBWkxaWEpoYkdFeERqQU1CZ05WQkFjTUJVdHZZMmhwTVJBd0RnWURWUVFLREFkMWMzUXVZMjl0TVJNdwpFUVlEVlFRRERBcDNaV0pvYjI5clgyTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUF1QTFYNnlqd00wbHBUQzdUc2ptUWVOOWh4R0puR1lzTWl4dHMzd041NUpnVEJTL1lBT0VFVTA4cmZpVlYKTDQrckh1KzFJZnNTQ0ZhYTRGQU9uSVVVTEdHV0U3OXk2ZFdsODQxekxDQ1ppeWlYK0JLRTQ3UTRtZDFVTHRKNQpQb1pzeVYzNzg0WVZRQ2ZMRzdZT3ZWKzhTV2YxbEdJZ2xjb1BsaTdDbmxQVWtNLzYwQk9IOVFkMlhEK1EwcTlZCmhCRFBGNVRwMzFBbEptYWpyeG5sVVV0SnJUR0o5K21vZzV4SnpvWndraXpUNXMzODBBdE5QRjJpbDJ1TjNrbzkKZm1WV2dBUjJRMXVhRVlpT3pONjJWd1pDbU9YUHVLdFVqSnJueDdJZWpNZ1FGV2YrbkIrc1BZQXIwZDUwWHdaOAp1eFJya0JZeGpPNElNSUkwQjdwbU41QW9ud0lEQVFBQm80SEZNSUhDTUIwR0ExVWREZ1FXQkJTWTVRZ2N5Q1FVCmowYnQ1aVVoL1o3VXdQblJNakNCa2dZRFZSMGpCSUdLTUlHSGdCU1k1UWdjeUNRVWowYnQ1aVVoL1o3VXdQblIKTXFGWnBGY3dWVEVMTUFrR0ExVUVCaE1DU1U0eER6QU5CZ05WQkFnTUJrdGxjbUZzWVRFT01Bd0dBMVVFQnd3RgpTMjlqYUdreEVEQU9CZ05WQkFvTUIzVnpkQzVqYjIweEV6QVJCZ05WQkFNTUNuZGxZbWh2YjJ0ZlkyR0NGQ1VGCndkZ0N5TTdicUVldmhXeS9vaklhaU1VRE1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQUQKZ2dFQkFIN2laV0pZSCtZbSs1RUtkc1NhT0xwY0RKM2RvZzg1d09XSWJkNWFMV25CeDN1R0RZWTl2aTY3ZEJ2egptM25sdmFra0htYTlpN20rTGtLdzl6dkdPNkdSMnlSTDNSaG9xaURsd0Y5WXFSWko5K0dEYkVlYjByb05rWXhqCjVLUHIzY0s4NmlEWWxnNjNFVU9PcVFCS3hpZjJIejhVVitpbkhOc01MWFhEUm5NUUdMOHpEYXUzNlVsNkUzUVoKZmt2TVhVWTA0Tng3d2xuMkVGb0pseHNlMmpZZmRyMEtNM2RRWjkyWGxudEI2R296a0FBSEpUbGQveWxBMjVqZgpsa2xrWTdwN2ZzaVc3MjlQKzdKL3U1U1YyZzhUOFVjTGZlS0s5MzhtNlRRQ0RZMHlmSjlCUmhHSzFWMmN2MkllCjNiR3Z5bzU1NjhlN3BKZFNoSVV1amRvak9iaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: ["*"]
        resources: ["*"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]

